Hw6
Altu-Bitu/Altu-Bitu_ pull request #8
Opened 2021-09-27 02:49 UTC by sonoasy

필수 1문제,선택 2문제 푼것 제출합니다

2021-09-27 11:49 UTC, HyunJiLim0406 requested changes
p1
수고하셨습니다! 근데 맞은 문제가 어떤 것이고 틀린 문제가 어떤 것인지 알려주시면 더 좋아요!
저희가 가끔 사소한 부분을 놓쳐서 맞은걸 틀렸다고, 틀린걸 맞았다고 생각할 수도 있거든요
코드에 코멘트 달아놓았으니 수정해주세요~
그리고 못푸신 문제는 샘플코드가 업로드 되면 주석 달아서 올려주세요

2021-09-27 11:49 UTC, HyunJiLim0406 commented on 9월21일 -부르트포스/10448.cpp
> +                }
n개의 수가 계속해서 들어오는 상황에서 매번 삼각수를 구해서 합을 구하는건 비효율적입니다.
전처리를 하는 방법이 있어요

2021-09-27 11:49 UTC, HyunJiLim0406 commented on 9월21일 -부르트포스/1107.cpp
> +    for (int i = 100; i < 500000; i++) {
이거 안돌아가지 않나요?

2021-09-27 11:49 UTC, HyunJiLim0406 commented on 9월21일 -부르트포스/1107.cpp
> +            }
매번 버튼 배열을 확인하면서 고장여부를 확인하는건 비효율적이에요
버튼은 겨우 10개입니다. 고장난 버튼을 한 번에 알 수 있는 방법은 무엇일까요?

2021-09-27 11:49 UTC, HyunJiLim0406 commented on 9월21일 -부르트포스/2108.cpp
> +    }
굳이 이렇게 안하셔도 돼요. 간단한 방법을 고민해볼까요?

2021-09-27 11:49 UTC, HyunJiLim0406 commented on 9월21일 -부르트포스/2108.cpp
> +    sort(vec.begin(), vec.end(), cmp);
맵을 벡터에 옮기는 과정 없이도 최빈값을 구하는 방법이 있어요! 한 번 고민해보세요

2021-09-27 11:49 UTC, HyunJiLim0406 commented on 9월21일 -부르트포스/2108.cpp
> +    }
주석이 없어서 코드를 이해하기 어렵습니다! 다음부터는 꼭 주석을 달아주세요

2021-09-27 11:49 UTC, HyunJiLim0406 commented on 9월21일 -부르트포스/2108.cpp
> +int main() {
하나하나 구할 때마다 출력하지 말고 각각의 연산을 함수로 만들면 어떨까요?

2021-09-27 13:51 UTC, sonoasy commented
앗 문제를 안적었네요.. 필수 2108번, 선택 2858,10448번 풀었고 1107번은 풀지 못한 문제입니다..! 푼 문제중에서 코멘트해주신 부분 수정했습니다!

2021-09-27 14:19 UTC, HyunJiLim0406 requested changes
p3(못 푼 문제 제외)
잘 수정하셨습니다!
그럼 20055 필수 문제 하나랑 선택 문제 하나 남은거네요!
샘플 코드 업로드 되면 주석달아서 업로드해주세요~

2021-09-27 14:19 UTC, HyunJiLim0406 commented on 9월21일 -부르트포스/10448.cpp
> +        }
flag를 바로 출력해도 되겠네요!

2021-09-27 14:19 UTC, HyunJiLim0406 commented on 9월21일 -부르트포스/10448.cpp
> +    }
👍

2021-09-27 14:19 UTC, HyunJiLim0406 commented on 9월21일 -부르트포스/2108.cpp
> +    }
이 과정을 다 합칠 수 있는 방법이 있긴 하지만 어렵다면 하지 않으셔도 좋아요!

2021-09-28 06:36 UTC, sonoasy commented
20055,1107번 주석 작성하여 제출합니다! 1107번에서 궁금한게 있는데 MAX_CHANNEL 의 값이  500000번 이상의 채널으로 이동한 후 가려는 채널로 이동할수 있어서 값을 크게 설정해야 하는것 같은데 이와같은 변수의 값은 임의로 답이 맞을때까지..?설정하는건지 궁금합니다!

2021-09-28 06:58 UTC, HyunJiLim0406 reviewed
p3
모두 확인했습니다!
MAX_CHANNEL의 값은 예상할 수 있어요!
입력으로 들어오는 최대 채널이 50만이라고 하네요. 그러면 시작 채널 100에서 버튼 하나로 계속 이동하면 이동 횟수는 499,900이 되겠네요! 버튼을 눌러서 채널을 이동한다고 해도 이 횟수 이상의 이동은 의미가 없어요.
만약 1,000,001 채널로 이동한다고 할게요! 그럼 이동 후 여기서 채널 50만까지 이동하려면 500,001번을 이동해야겠네요. 이건 100에서 이동하는 것보다 비효율적이기 때문에 그 이상은 고려할 필요가 없어요.
그래서 숫자를 정확히 하자면 1,000,000 - 100보다도 작은 값일텐데 그냥 백만으로 뭉뚱그려서 처리하는거예요!

머지해주세요~

2021-09-28 13:21 UTC, sonoasy commented
답변 감사합니다!

2021-09-28 13:21 UTC, merged